name: Build and deploy containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  leap-ai:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build leap rocm base image
        uses: aardsoft/ci-actions/kiwi-build@master
        with:
          image-directory: leap-rocm-base
          extra-repositories: |
            https://mirror.aardsoft.fi/opensuse/distribution/leap/15.6/repo/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/non-oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/oss
            https://mirror.aardsoft.fi/opensuse/update/leap/15.6/backports
            https://mirror.aardsoft.fi/opensuse//update/leap/15.6/sle
            https://download.opensuse.org/repositories/Virtualization:/containers/15.6
            https://repo.radeon.com/rocm/zyp/6.2.4/main/?ssl_verify=yes
